### ISSUE TITLE
Untranslated error messages (shipping address and probably more)

### ISSUE THREAD

**Issue by DanielRuf** [hyva-themes/magento2-react-checkout#274] opened 2022-02-22 10:10 UTC
It seems you only translate the `%1 is required` and replace the `%1` with the label but this leads to `company ist Pflicht` in our case where we show the error message in the banner.

formSectionErrors

https://github.com/hyva-themes/magento2-react-checkout/blob/main/src/reactapp/src/components/shippingAddress/components/ShippingAddressFormikProvider.jsx#L47

https://github.com/hyva-themes/magento2-react-checkout/blob/main/src/reactapp/src/components/shippingAddress/ShippingAddress.jsx#L40

https://github.com/hyva-themes/magento2-react-checkout/blob/main/src/reactapp/src/components/common/Form/TextInput.jsx#L53

![grafik](https://user-images.githubusercontent.com/827205/155110306-2f1a05bc-13d4-49a9-bb8a-445ea58b6a7d.png)

What would be the easiest and correct solution?

This should probably not the way to go:

![grafik](https://user-images.githubusercontent.com/827205/155110533-4765dff3-6fca-4bca-a53c-c2b290ce4e41.png)

**Comment by DanielRuf** [comment] 2022-02-22 10:16
So to me it seems these are never really or correctly translated as they should be.

**Comment by DanielRuf** [comment] 2022-02-22 10:18
Same probably also applies to billingAddress.

**Comment by rajeev-k-tomy** [comment] 2022-02-22 11:09
See the implementation `__()` which is used to translate strings within the app. https://github.com/hyva-themes/magento2-react-checkout/blob/main/src/reactapp/src/i18n/__.js#L13

As you see, we are translating the parameters too by self-invoking `__()` function.

```
stringLiteral = stringLiteral.replace('%1', __(dataToReplace));
```
So the only reason I can think of the reason behind those non-translating parameter is they are not passed via layout xml file: https://github.com/hyva-themes/magento2-react-checkout/blob/main/src/view/frontend/layout/hyvareactcheckout_reactcheckout_index.xml#L19

Make sure they exist in that list.

**Comment by DanielRuf** [comment] 2022-02-22 12:20
> So the only reason I can think of the reason behind those non-translating parameter is they are not passed via layout xml file: https://github.com/hyva-themes/magento2-react-checkout/blob/main/src/view/frontend/layout/hyvareactcheckout_reactcheckout_index.xml#L19
> 
> Make sure they exist in that list.

I already tried to add "company" to that list, this did not work at all.

**Comment by DanielRuf** [comment] 2022-02-22 12:28
Adding "company" to the xml + csv (company,aaa) we still get this:

![grafik](https://user-images.githubusercontent.com/827205/155132401-1d4b6561-5ca3-4d9e-9f22-d17cd5a79cce.png)

**Comment by DanielRuf** [comment] 2022-02-22 12:29
And it is definitely available there:

![grafik](https://user-images.githubusercontent.com/827205/155132609-015b3dfd-8fda-41c3-b73f-d3357f9f0078.png)

**Comment by rajeev-k-tomy** [comment] 2022-02-22 12:36
@DanielRuf Now i get it. It uses the company field name and not the label in the error message. A bug. It needs to be resolved. However, I assume this would be a tough one to fix

**Comment by rajeev-k-tomy** [comment] 2022-02-22 12:38
@DanielRuf Can you please add the exact scenario to reproduce the error. It would be helpful for me to quickly check on the issue or to suggest a solution in your case.

**Comment by DanielRuf** [comment] 2022-02-22 13:11
> @DanielRuf Can you please add the exact scenario to reproduce the error. It would be helpful for me to quickly check on the issue or to suggest a solution in your case.

In our case we just have to translate the "%1 is required" error messages to show them in the banner at the top (Message and ErrorMessage components).

For us the workaround with the patches (https://github.com/hyva-themes/magento2-react-checkout/issues/274#issuecomment-1047661770) is currently "ok" to have them properly translated.

**Comment by DanielRuf** [comment] 2022-02-22 13:12
> @DanielRuf Now i get it. It uses the company field name and not the label in the error message. A bug. It needs to be resolved. However, I assume this would be a tough one to fix

Ah ok. I will keep an eye on this issue here and we will add the workaround as patch files using cweagans/composer-patches, that is ok for us at the moment.

**Comment by rajeev-k-tomy** [comment] 2022-08-04 11:28
@DanielRuf I just checked this with the latest version of react checkout and it works just fine. Hence closing this issue.

**Closed by rajeev-k-tomy** 2022-08-04 11:28 UTC
