### ISSUE TITLE
Email validation scheme should allow `nullable`

### ISSUE THREAD

**Issue by wigman** [hyva-themes/magento2-react-checkout#188] opened 2021-09-27 08:36 UTC
When you start typing an email address and then clear the field, Formik throws an error, expecting a `string` value where `null` is given.
We should either cast the email to an empty string, or accept `.nullable()` for the `login.email` value.

**Comment by progammer-rkt** [comment] 2021-10-14 06:24
Hi @wigman

I tried this in `1.0.0-rc` branch right now and I could not reproduce this issue. When we clear out a email address field after filling it, it has an empty string value in the formik state and it is not `null`.

**Comment by rajeev-k-tomy** [comment] 2022-01-05 10:59
Closing this issue as it is fixed already and available in the stable release.

**Closed by rajeev-k-tomy** 2022-01-05 10:59 UTC
Labels: bug
